### ISSUE TITLE
How does the Vercel preview environment get the right `DATABASE_URL`?

### ISSUE THREAD

**Issue by StevenLangbroek** [neondatabase-labs/preview-branches-with-vercel#7]
Hey folks! Not really a bug report, more of a question. I got here by reading the [blog post](https://neon.tech/blog/branching-with-preview-environments), but am unable to locate exactly how a specific Vercel preview deployment becomes aware of the `DATABASE_URL` (for this specific Neon branch) it should connect to? Does the appending `DATABASE_URL` to `.env` during `migrate` get merged with the `.env` file pulled in with `vercel pull`?

**Comment by StevenLangbroek** [comment]
@m-abdelwahab any chance for input from Neon's side? :)

**Comment by m-abdelwahab** [comment]
> Does the appending DATABASE_URL to .env during migrate get merged with the .env file pulled in with vercel pull

@StevenLangbroek Yes, exactly! That's what this part does.

```
      - name: Run Prisma Migrate
        run: |
          touch .env
          echo DATABASE_URL=${{ steps.create_branch.outputs.db_url_with_pooler}}/neondb >> .env
          echo DIRECT_DATABASE_URL=${{ steps.create_branch.outputs.db_url}}/neondb >> .env
          npx prisma generate
          npx prisma migrate deploy

```

I just noticed that this part wasn't explained in the blog post. I'll make sure to update it. :)

 Thank you so much for reaching out, and sorry for the delayed response. I  didn't get notified when you created the issue :)

**Comment by StevenLangbroek** [comment]
Awesome, thanks @m-abdelwahab! We should be on production with our first use then early next week 🚀

**Comment by m-abdelwahab** [comment]
No problem @StevenLangbroek! Don't hesitate to reach out if you have any other questions or need help with anything :). You can reach out at support@neon.tech or DM me on [Twitter](https://twitter.com/thisismahmoud_)

**Comment by alxclark** [comment]
Hi @m-abdelwahab 👋🏼  Have you tried edge functions with this setup ? From my testing it seems like Vercel functions only pull the preview environment variables from the Vercel dashboard and don't reuse the local environment variables available at build time.

I'm curious if you found a way around that issue. Thanks!

**Comment by noqcks** [comment]
the .env doesnt actually work to add the DATABASE_URL to your deployment.

@alxclark this is what we're doing


```yaml
      - name: Create Neon Branch
        id: create-branch
        uses: neondatabase/create-branch-action@v5
        with:
          database: ${{ secrets.NEON_DATABASE_NAME }}
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          parent: "preview"
          branch_name: preview/pr-${{ github.event.number }}-${{ steps.branch-name.outputs.current_branch }}
          username: ${{ secrets.NEON_DATABASE_USERNAME }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Deploy App Preview
        id: deploy-app
        env:
          FILTER_APP: apps/app
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url_with_pooler }}
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.CI_VERCEL_TOKEN }}
          vercel build --token=${{ secrets.CI_VERCEL_TOKEN }}
          preview_url=$(vercel deploy --prebuilt \
            --no-wait \
            --yes \
            --token=${{ secrets.CI_VERCEL_TOKEN }} \
            -e DATABASE_URL=${{ steps.create-branch.outputs.db_url_with_pooler }} \
            -b DATABASE_URL=${{ steps.create-branch.outputs.db_url_with_pooler }} \
            -e VERCEL_GIT_COMMIT_REF=${{ steps.branch-name.outputs.current_branch }} \
            -b VERCEL_GIT_COMMIT_REF=${{ steps.branch-name.outputs.current_branch }} \
            -m githubCommitRef=${{ github.head_ref }} \
            -m githubCommitSha=${{ github.sha }} \
          )
          echo preview_url=$preview_url >> $GITHUB_OUTPUT
```
